---
- name: Initialise kali hosts
  hosts: all
  gather_facts: False

  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ansible_ssh_private_key_file: ansible/insecure_private_key
    # Set to `lolpassword`
    root_password: "$y$j9T$BoSIo.IkLu33dCk4Q13KL.$OmDK6zDSeogvQtk2p4.pB2rAaIm5yQj3G4eaq5aI0t6"
  # We want to be able to relax ssh auth because it's a testing environment
  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted

  tasks:
    - name: remove default vagrant user
      user:
        name: vagrant
        state: absent
        remove: yes
    - name: Set root pw
      user:
        name: root
        password: "{{root_password}}"
    - name: Remove ansible insecure key
      authorized_key:
        user: root
        state: absent
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
    - name: update sshd config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication.*no'
        line: 'PasswordAuthentication=yes'
      notify: restart_sshd
    
