---

- name: initialise server upon boot
  hosts: all
  gather_facts: False

  vars:
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    # FQDN of AD forrest
    ad_domain_name: megabank.local
    # Functional levels
    # https://docs.microsoft.com/en-us/powershell/module/addsdeployment/install-addsforest?view=win10-ps
    ad_domain_mode: Win2012R2
    ad_forrest_mode: Win2012R2
    # Domain Admin credentials to set
    domain_admin: vagrant
    domain_admin_password: vagrant
    # DFSR password
    # https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/cc731865(v%3Dws.11)
    domain_restore_password: LongPasswordGoesHere123

  tasks:
    - name: Wait for host to boot
      wait_for_connection:
        timeout: 900
    # We're on KVM - we want this box to know the local (hardware) clock is UTC
    - name: Set clock to use UTC
      win_command: bcdedit /set useplatformclock true
    # Sync clock with NTP
    - name: Configure NTP to use time.windows.com
      win_command: w32tm /config /manualpeerlist:time.windows.com /syncfromflags:MANUAL
    - name: Update NTP
      win_command: w32tm /config /update
    - name: Force a resync with NTP
      win_command: w32tm /resync
    - name: Set local admin password (becomes domain admin password)
      win_user:
        name: Administrator
        password: Password1
    # https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/adac/active-directory-administrative-center
    - name: Install ADAC
      win_feature:
        name: RSAT-AD-AdminCenter
        state: present
    # https://social.technet.microsoft.com/wiki/contents/articles/699.active-directory-domain-services-ad-ds-overview.aspx
    # We get this with `win_domain`, but we don't get the management tools (other than powershell utilities)
    # Lots of legacy sysadmins rely on these utilities
    - name: Install Domain Services
      win_feature:
        name: AD-Domain-Services
        include_management_tools: yes
        include_sub_features: yes
        state: present
    - name: Change the hostname to dc
      win_hostname:
        name: dc
      register: res
    - name: Reboot
      win_reboot:
      when: res.reboot_required
    - name: Setting DNS Servers
      win_dns_client:
        adapter_names: "*"
        ipv4_addresses: "127.0.0.1"
    - name: Create new Windows domain in a new forest with specific parameters
      win_domain:
        create_dns_delegation: no
        database_path: C:\Windows\NTDS
        dns_domain_name: '{{ ad_domain_name }}'
        domain_mode: '{{ ad_domain_mode }}'
        forest_mode: '{{ ad_domain_mode }}'
        safe_mode_password: '{{ domain_restore_password }}'
        sysvol_path: C:\Windows\SYSVOL
      register: domain_install
    - name: Reboot
      win_reboot:
      when: domain_install.reboot_required
      # Block until DC is live, so domain joins dont fail
    - name: Wait for host to boot
      wait_for_connection:
        timeout: 900
